### ISSUE TITLE
Unable to install the colors :(

### ISSUE THREAD

**Issue by fbcbl** [kaushikgopal/jetbrains_env#2]
Hey Kaushik! 

I was trying to install your base16 theme (after listening to your AndroidStudio podcast) but I'm not being able to. I created the link as you said :

```
ln -s ~/general/jetbrains_env/colors ~/Library/Preferences/AndroidStudio1.2/
```

But now where do I change the definition to adopt the base16 theme? 

I can't find anything on Theme settings or Color and Fonts settings.

Thank you!

**Comment by kaushikgopal** [comment]
Hey Fábio,

after you run that command, did you try restarting Android Studio? Typically, i have to restart Android Studio then when i proceed to **Default Preferences** > **Editor** > **Colors** and **Fonts**.  Under the dropdown for **Scheme** you should find the "kg_base16_ocean_dark" in that dropdown. Picking that should apply the theme.

Do note that i've noticed Android Studio being a little flaky when you paste the theme directly in the Preferences folder. It changes the format from xml to icls etc. and just removes the file during conversion. So make sure that the colors directory really has the theme file (typically .icls or .xml) **after** you restart AS. If it doesn't, then just try copying it to that directory again and restarting. 

That usually works for me :) 

Let me know if you're still having trouble.

**Comment by fbcbl** [comment]
Hey Kaushik!

Thank you! The problem was that I just copied the contents of the "color" folder. I also needed the files on the "options" folder. (Don't know which ones for sure, I just copied the entire content)

Thank you once again!

You're awesome!

**Comment by kaushikgopal** [comment]
awesome! glad that's working. 
btw i've been trying out a new theme inspired by the Visual Studio Code light theme ( `kg_code` ).

**Comment by fbcbl** [comment]
Cool! Btw, it was you that defined all the theme colors by yourself? ;)

**Comment by kaushikgopal** [comment]
no way! i only ported some of these to IntelliJ and modified them from the original. we should thank [Chris Kempson](http://chriskempson.github.io/base16/) for that :)

**Comment by h777arsh** [comment]
Hi Kaushik, thanks for the theme. it's awesome man. :smiley:
